In [ ]:
#下載 numpy，利用numpy 來新增 array 這個資料類型

In [1]:
a = [8,94,52,32,4]
b = [6,5,32,4,9]
result = []

for i in range(5):
    result.append(a[i]+b[i])

print(result)

[14, 99, 84, 36, 13]


In [2]:
#numpy 擴充資料結構 ndArray
#Array 可直接做陣列運算
import numpy as np
#透過list 建立 ndArray
a_array = np.array([8,94,52,32,4])
b_array = np.array([6,5,32,4,9])

a_array + b_array

array([14, 99, 84, 36, 13])

In [5]:
import random

#list comprehension
[random.randint(50,100) for i in range(5)]

[82, 56, 57, 60, 100]

In [6]:
#使用numpy  random建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([94, 57, 87, 74, 63])

In [7]:
np.random.randint(50,high=100,size=[50,5])

array([[62, 63, 93, 96, 93],
       [79, 73, 83, 67, 78],
       [85, 83, 78, 70, 76],
       [81, 65, 66, 86, 67],
       [76, 73, 76, 70, 77],
       [55, 50, 80, 80, 83],
       [81, 74, 50, 58, 78],
       [55, 72, 52, 58, 74],
       [51, 98, 74, 74, 75],
       [80, 85, 83, 98, 80],
       [63, 67, 51, 51, 83],
       [93, 80, 75, 66, 58],
       [63, 86, 92, 52, 78],
       [99, 54, 61, 55, 78],
       [69, 68, 58, 73, 65],
       [75, 82, 92, 57, 99],
       [77, 76, 71, 50, 55],
       [88, 81, 66, 80, 84],
       [52, 62, 57, 74, 93],
       [65, 81, 82, 54, 93],
       [89, 92, 67, 57, 61],
       [70, 77, 94, 73, 76],
       [99, 80, 75, 74, 71],
       [60, 81, 55, 93, 60],
       [72, 50, 96, 62, 50],
       [53, 84, 68, 95, 95],
       [72, 56, 63, 83, 50],
       [54, 85, 52, 55, 92],
       [80, 70, 95, 76, 93],
       [61, 59, 90, 91, 58],
       [98, 82, 53, 83, 64],
       [75, 77, 95, 82, 83],
       [52, 74, 51, 55, 55],
       [92, 79, 58, 51, 60],
       [80, 57